language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE="django_rbe.settings"
install:
  # - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt
  # - pip install https://github.com/dcramer/pyflakes/tarball/master
  # - pip install -q -e . --use-mirrors
before_script:
#   - "pep8 --exclude=migrations --ignore=E501,E225 src"
#   - pyflakes -x W src
script:
  - python manage.py test